# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Georgina Elizabeth Castorena Rojas
title: Informatics Engineering Student
email: georgina.castorena2907@gmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: https://github.com/CastorenaG
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  CastorenaG
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: georgina-castorena-573017265
#credly: https://www.credly.com/users/georgina-elizabeth-castorena-rojas/badges
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
- title: Credly
  icon: fas fa-award
  url: https://www.credly.com/users/georgina-elizabeth-castorena-rojas/badges


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/georgina_castorena.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, My name is Georgina, I love networks, servers and cibersecurity. I would like to study a master in cybersecurity.
  I like to work in theams and I lear fast.I like learn every day. Likewise, I also have experience working with servers and a little bit with networks.
  
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project Particles
        #link: https://github.com/CastorenaG/proyectoParticulas
        #link_text: Link Text
        #additional_links:
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
          #  icon: fab fa-github
          #  url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          #- title:  Github page for project (eg. sproogen/modern-resume-theme)
          #  icon: fab fa-github
          #  url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Is a project that works with QTDesigner, Python and Algorithms.
        description: | # this will include new lines to allow paragraphs
          This program draws different colored dots, you can select the color using RGB, you can also manually enter the data such as origin, destination, speed and so on. And visualize it in different ways as well as order the information.
#- title: Experience
    #layout: list
    #content:
      #- layout: right
        #title: Company name
        #sub_title: Job title
        #caption: Date Range (eg. November 2016 - present)
        #link: Link to company (optional)
        #quote: >
          #Short description of the company (optional)
        #description: | # this will include new lines to allow paragraphs
          #Description of role"""

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: University of Guadalajara
        sub_title: Informatics Engineering
        caption: 2020 - At the moment
        quote: >
          Located within the University of Guadalajara, is a renowned academic institution specializing in the fields of exact sciences and engineering.
        description: | # this will include new lines to allow paragraphs
          Within the time that I have been in the career I have learned an incredible variety of things, such as working as a team, but at the same time individually, being self-taught and responsible. One of the things I like the most about my career is that you always have to be current and, as a result, learn something new every day.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I possess a keen interest in research and consider myself proficient in conducting investigations. Additionally, I have a strong inclination towards remaining proactive and well-prepared for any given situation.
      I exhibit exceptional teamwork skills, displaying empathy and proficiency in conflict resolution. Furthermore, I prioritize organizational efficiency, diligently managing my time to meet deadlines and optimize productivity.
      I demonstrate adaptability and a rapid learning curve, allowing me to seamlessly integrate into new environments and acquire new skills. Moreover, I am presently at a B1 proficiency level in the English language.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
